package com.etema.ragnarmmo.combat.api;

/**
 * RagnarTargetCandidate - A lightweight representation of a target entity suggested
 * by the client or generated by an internal resolver.
 */
public record RagnarTargetCandidate(
        int entityId,
        RagnarTargetSource source,
        double score
) {
    /**
     * Default constructor for simple client-suggested targets.
     */
    public static RagnarTargetCandidate from(int entityId, RagnarTargetSource source) {
        return new RagnarTargetCandidate(entityId, source, 0.0D);
    }
}
